on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install the Linode CLI
        uses: ./
        with:
          token: "${{ secrets.LINODE_TOKEN }}"
      - name: Run an authenticated command
        run: linode-cli linodes ls > /dev/null